---
title: "EDA"
author: "Gemma Bargalló Solé"
date: "2026-04-20"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float:
      position: left
    toc_depth: 5   
  word_document: default
  pdf_document: default
---

```{r packages import, warning=FALSE, message=FALSE}
library(tidyverse)
library(nanoparquet)
library(here)
library(scales)
library(naniar) 
library(skimr) 
library(patchwork)
```

# 1. Data Import

```{r}
# Final dataset import
wfc <- read_parquet(here("Data", "wfc_consolidated_landcover.parquet"))

# Variable changes
wfc <- wfc %>%
  mutate(
    causa = as.factor(causa),
    provincia = as.factor(provincia),
    land_cover_id = as.factor(land_cover_id),
    month_detected = factor(month_detected, levels = c("gen", "feb", "mar", "abr", "mai", "jun", 
                                                       "jul", "ago", "set", "oct", "nov", "des"))
  )

glimpse(wfc)
```

# 2. Missing Data Analysis

```{r}
### 2.1. Overall Missingness
# Missings totals al dataframe
res_missing <- miss_var_summary(wfc)
print(res_missing)

### 2.2. Visualizing Missing Patterns
gg_miss_var(wfc) + 
  labs(title = "Missing Values by Variable")

vis_miss(wfc, warn_large_data = FALSE) +
  theme(axis.text.x = element_text(angle = 90))
```


# 3. Descriptive Statistics 

```{r}
### 3.1. Detailed Summary Table
skim(wfc)
```


# 4. Univariate Analysis (Distributions)
## 4.1. Numeric Variables (Outliers check)
```{r}
numeric_vars <- c("superficie_total_forestal", "tx", "tn", "ppt", "altitude_z", "thermal_amplitude")

wfc %>%
  select(all_of(numeric_vars)) %>%
  pivot_longer(everything()) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot(fill = "orange", alpha = 0.7) +
  facet_wrap(~name, scales = "free") +
  theme_minimal() +
  labs(title = "Boxplots of Numeric Variables (Outlier Detection)", x = "", y = "Value")
```

## 4.2. Categorical Variables (Frequency)

```{r}
# Gràfic de barres per a la causa i la província
p1 <- ggplot(wfc, aes(x = fct_infreq(provincia))) +
  geom_bar(fill = "steelblue") +
  labs(title = "Fires by Province", x = "Province")

p2 <- wfc %>% 
  count(causa) %>%
  mutate(causa = fct_reorder(causa, n)) %>%
  ggplot(aes(x = causa, y = n)) +
  geom_col(fill = "firebrick") +
  coord_flip() +
  labs(title = "Fires by Cause", x = "Cause")

p1 / p2 # Gràcies a 'patchwork' posem un sobre l'altre
```

